const testToken =
  'Bearer%20eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0QHRlc3QuY29tIiwiYXV0aCI6IlJPTEVfVVNFUiIsImV4cCI6MTc0MjAzNjA4MSwiaWF0IjoxNzQyMDMyNDgxLCJqdGkiOiIxOTAxZGY2Ni1kYzJjLTRhNGItOTdhOS0wMjkwMzYyYzcwZjcifQ.ZcHyJVEdCAY1Xarp8F2rq9KnPWSg9e-7f9KJWpHtsoQ';

export default testToken;
